doc.type.html
script
filename=covidstrings25.js
java.awt graphics
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio (audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new button(change color)
public fun with graphics()
color panel=new j panel();
this add (panel,center)
button panel
new  panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r=newrandom();
colorpanel.setbackground(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextInt(13),(rnextint(13)))
num teams
total players=players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e){
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string []args)
jframe f = new covid strings25()
f.set title(covid strings25)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult ==x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covid strings team list25=[burgundy rebuilders ,yellow moxie ,black night riders ,red protein spikers ,purple brave hearts,green peacemakers,turquoise waves,orange rna messengers]
covid strings multiple choicelist25=[1:a resurface b hide c shapeshift d go on oxycontin ,2:a speech b comparing and contrasting the25th amendment c infrastructure opportunities d americas allies getting nuclear weapons,3:a pandemic b january 6th  c world poker tour  d coronavirus d more than that,4:a third b fourth c second d fifth,5:a stress b fatigue c boredom d impulse buying,6:a ten  b twelve  c six  d two,7:a mulberry silk b vaccines c dairy queen blizzards d clones of dr.oz,8:a2 and a half  b5 c17 and a half d3,9:a88 d365 c10 d93 million,10:a immediate b long c short d intermediate ,11:a6 b30 c5.8 d10,12:a75% b51% c5% d near,13:a misinformation b disinformation c facts d truths,14:a prices for groceries b supply of christmas presents c lifespans d trust in government,15:a2016 election b2020 election c2012 election d covid]
covid strings phrase list25=[ non-concatenated strings  "covid can hide apparently for at least a year after infection"
"not only did one strain of flu disappear during covid a second one may disappear with new vaccines"
"chronic stress might be an unintended consequence of the pandemic on everyone"
"just as worrisome long covid can actually remain in patients for up to two years"
"even more concerning is that more than17 and a half million americans are living with long covid"
"it may even be the case that most long term covid sufferers never officially tested positive for the virus"
"the problem may involve testing being viewed as safe if its near perfect"
"four years later covid is at least more manageable"
concatenated strings 
"backlash"+"has"+"made"+"the"+"next"+"pandemic"+"a"+"harder"+"thing"+"to"+"deal"+"with"
"covid"+"at"+"least"+"has"+"mrna"+"vaccines"+"on"+"hand"
"being"+"unknowlingly"+"contagious"+"for"+"10"+"days"+"is"+"another"+"concern"
"covid"+"in"+"terms"+"of"+"speech"+"is"+"even"+"being"+"put"+"before"+"the"+"supreme"+"court"
"even"+"more"+"concerning"+"is"+"the"+"fact"+"that"+"5.8"+"million"+"kids"+"have"+"long"+"covid"
"covid"+"misinformation"+"is"+"still"+"causing"+"a"+"problem"+"without"+"ai"
"ai"+"powered"+"covid"+"misninformation"+"then"+"is"+"an"+"even"+"bigger"+"problem"
"the"+"consequence"+"of"+"this"+"is"+"decreased"+"lifespans"]
covid strings25 math problemslist=[ non-concatenated "if the line had a slope of1 and7 tenths with a y intercept of 1/2 what would the y coordinate be if the x coordinate is5"?,"if the point (5,9) was reflected across the x axis what is the new point"?,"if the previous point was rotated90 degrees clockwise what is the new point"?,"if the previous point was rotated270 degrees counterclockwise what is the new point"?,"if the previous point was translated2 units across the x axis and4 units across the y axis what is the new point"?,"if the previous point was translated5 units across the x axis and8 units across the y axis what is the new point"?,"if a second point was drawn at4 what would the y coordinate be"?,"if the second point wanted to intersect with the original point how much would it have to be translated by"?,
concatenated "if"+"an"+"american"+"physcological"+"association"+"poll"+"found"+"78"+"percent"+"of"+"adults"+"report"+"increased"+"stress"+"due"+"to"+"covid"+"what"+"percent"+"dont"?,
"if"+"67"+"percent"+"strongly"+"tie"+"the"+"stress"+"to"+"covid"+"what"+"percent"+"dont"?,"if"+"the"+"margin"+"of"+"error"+"is"+"3.434"+"percent"+"what"+"is"+"the"+"range"?,"if"+"57"+"percent"+"are"+"surprised"+"that"+"17"+"million"+"americans"+"are"+"living"+"with"+"long"+"covid"+"what"+"percent"+"arent"?,"if"+"17"+"percent"+"are"+"strongly"+"surprised"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"1.717"+"percent"+"what"+"is"+"the"+"range"?]
covid strings scrambled phrase list25=["ovicd"+"rmna"+"acvines","5.8"+"limon"+"diks"+"avhe"+"ovcid"]
bonus question=("if the new point wanted to intersect with the first transformed point how many units would have to be translated"?)
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
gradientunits=userspaceonuse
x1=0
y1=1/2
x2=5
y2=x2*1.7+1/2
top offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fecomponenttransfer>
<fefunccovidstrings type=linear slope>=1
function1=number of americans living with long covid
if function1slope<0:
return inverse relationship
else:
return no or direct relationship
transformationlist=[reflection,rotation,translation]
if reflection==x axis:
shift x axis
else:
shift y axis
if rotation==90 degrees clockwise:
shift 90 degrees clockwise 
else:
remain
if rotation==270 degrees counterclockwise:
shift 270 degrees counterclockwise
else:
remain
if translation==(2,4):
shift 2 units right and 4 units up
else:
remain
if translation==(5,8)
shift 5 units right and 8 units up
else:
remain
if translation(4,x)==difference of 9
find xvalue
else:
remain
if instersection(4,13)(12,21)==translation:
find number of units
else:
remain
if intsersection(4,13)(7,13)==translation:
find number of units
else:
remain
substring(start,end)
userin.multiple choice
if (s1.length())!=s2.length: 
return false
if s1.length()==s2.length:
return true
char[]arr1=s1.tochararray
char[]arr2= s2.tochararray
arrays.sort(arr1)
arrays.sort(arr2)
if selectedanswer=not correct
return false
else 
return true
if selectedanswer=correct:
return true
else:
return false
function2=(covid,car prices) 
if function2.slope x1*y1 >=1:
return direct
else:
return inverse or no relationship
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet) 
if users team wins covid strings25 
console log users team wins covid strings25 
else
return game over
return filename
