doc.type.html
script
filename=covid strings 25 key words.js
covid strings 25 key word list=[a year after infection,put before supreme court,backlash,disappear,unintended consequence,100–78,mrna on hand,million americans long covid,unknowingly contagious,never tested positive,million kids long covid,testing safe perfect,years later,consequence decreased,ai misinformation]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
covid strings25 reference list=[a:hidden covid virus found more than a year after infection (msn.com),b:covid-era case on free speech to test supreme court (msn.com),c:covid backlash could leave the u.s.less ready for the next pandemic (msn.com),d:as covid spread,a strain of flu disappeared.now scientists say a second could go too (msn.com),e:covid pandemic unleashed a pervasive danger,suggests harrowing new study-and its not the virus (msn.com),f:stress in america 2020:a national mental health crisis (apa.org),g:long covid:virus remain in patients for up to two years after exposure,study finds (msn.com),h:mrna tech:expanding from covid vaccines to rsv, hiv,flu and cancer (axios.com),
i:alarming rise in long covid symptoms in us adults,cdc reports warns (msn.com),j:how long are you contagious with covid-19? (msn.com),k:many long covid sufferers never even tested positive for the virus (msn.com),l:millions of kids have long covid and symptoms can be heartbreaking (msn.com),m:heres why rapid covid tests are so expensive and hard to find propublica,n:covid-19:what changed in four years since pandemic was announced? (yahoo.com),o:infrastructure investment and jobs act-wikipedia,p:covid helped cause the biggest drop in u.s. life expectancy since wwii|pbs newshour,r:artificial intelligence struggles to moderate covid misinformation |covisualize (formally the coronavirus visualization team) (harvard.edu)]
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
j=pc.create script(j);
j.attributes.add(foobar,{type:entity});
j.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.create script(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
l=pc.create script(l);
l.attributes.add(foobar,{type:entity});
l.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
r=pc.create script(r);
r.attributes.add(foobar,{type:entity});
r.prototype.initialize=function() 
console.log(this.foobar.name)
return filename
