doc.type.html
script
filename=covidstrings25gamecode.js
java.awt graphics
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio (audio_file mp3)
audio.play 
jbutton random button
new jbutton (set random color)
private final j button option button=
new j button(change color)
public fun with graphics(){
jpanel color panel=new j panel();
this add (panel,center)
jpanel button panel=
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r=newrandom();
colorpanel.setbackground(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextInt(13),(rnextint(13)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e){
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string []args)
jframe f = new covid strings25()
f.set title(covid strings25)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult ==x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covid strings team list25=[burgundy,yellow,black,red,purple,green,turquoise,orange]
covid strings multiple choicelist25=[ non-concatenated 1:a resurface b hide c shapeshift d go on oxycontin ,2:a speech b comparing and contrasting the25th amendment c infrastructure opportunities d americas allies getting nuclear weapons,3:a pandemic b january 6th  c world poker tour  d coronavirus d more than that,4:a third b fourth c second d fifth,5:a stress b fatigue c boredom d impulse buying,6:a ten  b twelve  c six  d two,7:a mulberry silk b vaccines c dairy queen blizzards d clones of dr.oz,8:a2 and a half  b5 c17 and a half d3,9:a88 d365 c10 d93 million,10:a immediate b long c short d intermediate ,11:a6 b30 c5.8 d10,12:a75% b51% c5% d near,13:a misinformation b disinformation c facts d truths,14:a prices for groceries b supply of christmas presents c lifespans d trust in government,15:a2016 election b2020 election c2012 election d covid]
covid strings phrase list25=[covid can hide apparently for at least a year after infection
not only did one strain of flu disappear during covid a second one may disappear with new vaccines
chronic stress might be an unintended consequence of the pandemic on everyone
just as worrisome long covid can actually remain in patients for up to two years
even more concerning is that more than17 and a half million americans are living with long covid
it may even be the case that most long term covid sufferers never officially tested positive for the virus
the problem may involve testing being viewed as safe if its near perfect 
four years later covid is at least more manageable
concatenated
Backlash+Has+Made+The+Next+Pandemic+A+Harder+Thing+To+Deal+With
COVID+At+Least+Has+MRNA+Vaccines+On+Hand
Being+Unknowlingly+Contagious+For+10+Days+Is+Another+Concern
Covid+In+Terms+Of+Speech+Is+Even+Being+Put+Before+The+Supreme+Court
Even+More+Concerning+Is+The+Fact+That+5.8+Million+Kids+Have+Long+Covid
Covid+Misinformation+Is+Still+Causing+A+Problem+Without+Ai
Ai+Powered+Covid+Misninformation+Then+Is+An+Even+Bigger+Problem
The+Consequence+Of+This+Is+Decreased+Lifespans]
Covid Strings25 Math ProblemsList=[If The Line Had A Slope Of1 And7 Tenths With A Y Intercept Of 1/2 What Would The Y Coordinate Be If The X Coordinate Is5?,If The Point (5,9) Was Reflected Across The X Axis What Is The New Point?,If The Previous Point Was Rotated90 Degrees Clockwise What Is The New Point?,If The Previous Point Was Rotated270 Degrees Counterclockwise What Is The New Point?,If The Previous Point Was Translated2 Units Across The X Axis And4 Units Across The Y Axis What Is The New Point?,If The Previous Point Was Translated5 Units Across The X Axis And8 Units Across The Y Axis What Is The New Point?,If A Second Point Was Drawn At4 What Would The Y Coordinate Be?,If The Second Point Wanted To Intersect With The Original Point How Much Would It Have To Be Translated By?,If+A+American+Physcological+Association+Poll+Found+78+Percent+Of+Adults+Report+Increased+Stress+Due+To+Covid+What+Percent+Dont?,
If+67+Percent+Strongly+Tie+The+Stress+To+Covid+What+Percent+Dont?,If+The+Margin+Of+Error+Is+3.434+Percent+What+Is+The+Range?,If+57+Percent+Are+Surprised+That+17+Million+Americans+Are+Living+With+Long+Covid+What+Percent+Arent?,If +17+Percent+Are+Strongly+Surprised+What+Percent+Is+Mild?,If+The+Margin+Of+Error+Is+1.717+Percent+What+Is+The+Range?]
Covid Strings Scrambled Phrase List25=[Ovicd+Rmna+Acvines,5.8+Limon+Diks+Avhe+Ovcid]
Userin.Select Team
Import Meta.
Class MyClass
Constructor (Non-Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
If Problem=Multiple Choice 
Select From Multiple Choice
Else
Prompt 
Log
Myclass=New.Myclass(Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
If Problem=Multiple Choice 
Select From Multiple Choice
Else
Prompt 
Log
Import Syntax
Chart JS 
Def Gradient
id=mygradient
gradientunits=userspaceonuse
if selectedanswer=not correct
return false
else 
return true
if selectedanswer=correct:
return true
else:
return false
return filename
